[package]
name = "wasm2rs"
description = "Compiler library for translating WebAssembly to Rust"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
wasmparser = "0.201.0"
rayon = "1.9.0"
