[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[workspace]
resolver = "2"
members = [
    "crates/compiler",
    "crates/rt",
    "tests/compiler",
    "tests/spec",
]
default-members = ["crates/compiler", "crates/rt"]

[workspace.dependencies]
wasm2rs-rt = { path = "crates/rt" }
