[package]
name = "wasm2rs-rt"
description = "Runtime support library for WebAssembly modules translated to Rust"
version.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
