//! Types used in stack traces.

/// Stores WebAssembly-specific information for a native stack frame corresponding to a Rust
/// function generated by `wasm2rs`.
#[derive(Clone, Copy, Debug)]
#[non_exhaustive]
pub struct WasmFrame {
    /// Indicates the WebAssembly function that a native stack frame refers to.
    pub symbol: &'static crate::symbol::WasmSymbol,
    /// A byte offset from the start of the [code section entry] to the WebAssembly instruction.
    ///
    /// [code section entry]: crate::symbol::WasmSymbolKind::Defined::offset
    pub offset: u32,
    //location: &'static struct FileLocation { file: &'static str, line: u32, column: u32 },
}

impl WasmFrame {
    /// Creates a new stack frame with a [`WasmSymbol`] and a byte offset to the original
    /// WebAssembly instruction.
    ///
    /// Calls to this function are emitted when `wasm2rs` is configured to include stack trace
    /// information in the translated code.
    ///
    /// [`WasmSymbol`]: crate::symbol::WasmSymbol
    pub const fn new(symbol: &'static crate::symbol::WasmSymbol, offset: u32) -> Self {
        Self { symbol, offset }
    }
}

impl core::fmt::Display for WasmFrame {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{} @ {:#X}", self.symbol, self.offset)
    }
}
